import { Inter } from "next/font/google";
import { Providers } from "./chakraproviders";
import Header from "./components/Header";
import Providerss from "./Redux/providerss";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providerss>
          <Providers>
            <Header />
            {children}
          </Providers>
        </Providerss>
      </body>
    </html>
  );
}
